### ISSUE TITLE
build images for all supported pg versions

### ISSUE THREAD

**Issue by ChuckHend** [tembo-io/pgmq#137]
Publish docker images for all the versions that we run tests for / are supported.

**Comment by tavallaie** [comment]
I thinks with docker like this: 
``` yaml
ARG PG_VERSION
ARG PGRX_VERSION

FROM quay.io/coredb/pgrx-builder:pg${PG_VERSION}-pgrx${PGRX_VERSION}

WORKDIR /app

COPY --chown=postgres:postgres . .

ARG EXTENSION_NAME
ARG EXTENSION_VERSION

RUN cd extension && cargo pgrx package

# Add commands to build and push Docker image
FROM postgres:${PG_VERSION}

COPY --from=0 /app/target/release/${EXTENSION_NAME}-${EXTENSION_VERSION}.so /usr/lib/postgresql/${PG_VERSION}/lib/

ENTRYPOINT ["postgres"]

```

and action like this: 
```yaml
name: Build and Push Docker Images

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_version: [13, 14, 15]  # Add all supported PG versions
        pgrx_version: [0.9.8]     # Add relevant PGRX versions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          yourdockerhubusername/pgmq:${{ matrix.pg_version }}-${{ matrix.pgrx_version }}
          ${{ steps.set-latest.outputs.latest_tag }}
      build-args: |
        PG_VERSION=${{ matrix.pg_version }}
        PGRX_VERSION=${{ matrix.pgrx_version }}

    - name: Set latest tag
      id: set-latest
      run: |
        PG_VERSIONS=(${{ matrix.pg_version }})
        HIGHEST_PG_VERSION=$(echo ${PG_VERSIONS[*]} | tr ' ' '\n' | sort -nr | head -n1)
        if [ "${{ matrix.pg_version }}" == "$HIGHEST_PG_VERSION" ]; then
          echo "::set-output name=latest_tag::yourdockerhubusername/pgmq:latest"
        else
          echo "::set-output name=latest_tag::"
        fi

```

We can achieve this, but I'm not sure where to make those changes. Should we create a new action or edit the one we already have?
